name: WebServerVDT
on:
  push:
    branches: [ "main" ] 
jobs:
  
  build-and-push:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Lowercase Repo Name
        run: |
          echo "REPO_LC=${GITHUB_REPOSITORY,,}" >> $GITHUB_ENV

      - name: Log in to GHCR
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Build and Push
        uses: docker/build-push-action@v5
        with:
          context: .
          push: true
          tags: ghcr.io/${{ env.REPO_LC }}:latest


  deploy:
    needs: build-and-push 
    runs-on: ubuntu-latest
    steps:
      - name: Deploy to VPS via SSH
        uses: appleboy/ssh-action@v1.0.3
        with:
          host: ${{ secrets.SERVER_IP }}
          username: ${{ secrets.SERVER_USER }} 
          key: ${{ secrets.SSH_PRIVATE_KEY }} 
          script: |
            # Mở giới hạn OS trước khi chạy server
            ulimit -n 65535 || true
            sysctl -w net.core.somaxconn=65535 || true
            sysctl -w net.ipv4.tcp_max_syn_backlog=65535 || true

            echo ${{ secrets.GITHUB_TOKEN }} | docker login ghcr.io -u ${{ github.actor }} --password-stdin

            REPO_LOWER=$(echo "${{ github.repository }}" | tr '[:upper:]' '[:lower:]')

            docker pull ghcr.io/$REPO_LOWER:latest

            docker stop webserver || true
            docker rm webserver || true

            docker run -d \
              --name webserver \
              -p 8081:8081 \
              --ulimit nofile=65535:65535 \
              -v /root/www_download:/app/www/download \
              -v /root/uploads:/app/www/upload \
              --restart always \
              ghcr.io/$REPO_LOWER:latest